# Лабораторная работа 1. Методы сортировки.
    Выполнила: Катанаева Иулитта
    Группа: БВТ1903
    Вариант: 3

### Задание.
Реализовать метод сортировки обменом для строк числовой матрицы в соответствии с заданием. Добавить реализацию быстрой сортировки (quicksort). Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки, используемой в Python.

In [3]:
# Импортирование нужных библиотек
import numpy as np
import time
import random

In [4]:
# Реализация матрицы с помощью двумерного массива NumPy
SIZE = 500
matrix = np.zeros((SIZE, SIZE))

# Генерация матрицы случайных чисел
for i in range (0, SIZE):
    for j in range (0, SIZE):
        matrix[i][j] = random.randrange(-1000, 1000)

# Вывод сгенерированной матрицы
print(matrix)

[[-172. -796. -776. ...  436.  169.  759.]
 [ 763.  673.   54. ... -364.  556.  326.]
 [ 341. -853.  800. ... -440.  957.  291.]
 ...
 [ 592. -374. -210. ... -557. -451.  914.]
 [-995. -603. -151. ... -874.  820.  596.]
 [-735.  357.  539. ... -509.  -31. -336.]]


In [5]:
# Функция сортировки обменом (пузырьковая сортировка)
def bubblesort(row):
    i = row.size - 1
    while (i > 0):
        j = 0
        while (j < i):
            if (row[j] > row[j + 1]):
                temp = row[j]
                row[j] = row[j + 1]
                row[j + 1] = temp
            j = j + 1
        i = i - 1

In [6]:
# Функция возвращает индекс опорного элемента
def partition(row, low, high):
    x = row[high]
    i = low - 1
    j = low
    tmp = 0
    while j < high:
        if row[j] <= x:
            i = i + 1
            tmp = row[i]
            row[i] = row[j]
            row[j] = tmp
        j = j + 1
    tmp = row[high]
    row[high] = row[i + 1]
    row[i + 1] = tmp
    return i + 1 

# Функция быстрой сортировки
def quicksort(row, low, high):
    if low < high:
        p = partition(row, low, high)
        quicksort(row, low, p - 1)
        quicksort(row, p + 1, high)

In [7]:
# Функция, формирующая отсортированную матрицу
def using_sort(matrix, sort_type = 'none'):
    sort_matrix = np.zeros(matrix.shape)
    atime = 0;
    
    # Если выбрана сортировка обменом
    if sort_type == 'bubble':
        sort_matrix = matrix.copy()
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            bubblesort(sort_matrix[i,:])
        t2 = time.process_time()
        atime = t2 - t1
    
    # Если выбрана быстрая сортировка
    elif sort_type == 'quick':
        sort_matrix = matrix.copy()
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            quicksort(sort_matrix[i,:], 0, sort_matrix.shape[1] - 1)
        t2 = time.process_time()
        atime = t2 - t1
    
    # В противном случае выбирается стандартная функция сортировки NumPy
    else:
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            sort_matrix[i] = np.sort(matrix[i,:])
        t2 = time.process_time()
        atime = t2 - t1

    # Вывод результатов на экран и их возвращение функцией
    print('Время выполнения сортировки (в секундах): ', atime)
    print('Результат:\n', sort_matrix, "\n")
    return sort_matrix

In [8]:
# Вызов каждого метода сортировки с выводом времени выполнения и отсортированной матрицы

# Сортировка обменом
print('Сортировка обменом')
a = using_sort(matrix, 'bubble')

# Быстрая сортировка
print('Быстрая сортировка')
a = using_sort(matrix, 'quick')

# Стандартная функция сортировки
print('Стандартная функция сортировки NumPy')
a = using_sort(matrix)

Сортировка обменом
Время выполнения сортировки (в секундах):  104.390625
Результат:
 [[ -996.  -993.  -991. ...   993.   993.   996.]
 [ -997.  -995.  -992. ...   984.   988.   990.]
 [ -992.  -991.  -991. ...   993.   997.   997.]
 ...
 [ -998.  -997.  -996. ...   998.   998.   999.]
 [ -995.  -994.  -990. ...   993.   994.   999.]
 [-1000. -1000.  -999. ...   994.   996.   998.]] 

Быстрая сортировка
Время выполнения сортировки (в секундах):  4.1875
Результат:
 [[ -996.  -993.  -991. ...   993.   993.   996.]
 [ -997.  -995.  -992. ...   984.   988.   990.]
 [ -992.  -991.  -991. ...   993.   997.   997.]
 ...
 [ -998.  -997.  -996. ...   998.   998.   999.]
 [ -995.  -994.  -990. ...   993.   994.   999.]
 [-1000. -1000.  -999. ...   994.   996.   998.]] 

Стандартная функция сортировки NumPy
Время выполнения сортировки (в секундах):  0.046875
Результат:
 [[ -996.  -993.  -991. ...   993.   993.   996.]
 [ -997.  -995.  -992. ...   984.   988.   990.]
 [ -992.  -991.  -991. ...   99