# Лабораторная работа 1. Методы сортировки.
    Выполнила: Катанаева Иулитта
    Группа: БВТ1903
    Вариант: 3

### Задание.
Реализовать метод сортировки обменом для строк числовой матрицы в соответствии с заданием. Добавить реализацию быстрой сортировки (quicksort). Оценить время работы каждого алгоритма сортировки и сравнить его со временем стандартной функции сортировки, используемой в Python.

In [8]:
# Импортирование нужных библиотек
import numpy as np
import time
import random

In [10]:
# Реализация матрицы с помощью двумерного массива NumPy
SIZE = 500
matrix = np.zeros((SIZE, SIZE))

# Генерация матрицы случайных чисел
for i in range (0, SIZE):
    for j in range (0, SIZE):
        matrix[i][j] = random.randrange(-1000, 1000)

# Вывод сгенерированной матрицы
print(matrix)

[[ 426. -195. -604. ... -956.  859. -490.]
 [-338.  527.  925. ...  458.  917. -461.]
 [ 592.  182.  763. ...  378.  -92.  199.]
 ...
 [-643.  613.  349. ...  300. -587.  762.]
 [  -5.  322.  -20. ... -860.  803. -431.]
 [-810. -824. -871. ...  393.  451.  267.]]


In [11]:
# Функция сортировки обменом (пузырьковая сортировка)
def bubblesort(row):
    i = row.size - 1
    while (i > 0):
        j = 0
        while (j < i):
            if (row[j] > row[j + 1]):
                temp = row[j]
                row[j] = row[j + 1]
                row[j + 1] = temp
            j = j + 1
        i = i - 1

In [12]:
# Функция возвращает индекс опорного элемента
def partition(row, low, high):
    x = row[high]
    i = low - 1
    j = low
    tmp = 0
    while j < high:
        if row[j] <= x:
            i = i + 1
            tmp = row[i]
            row[i] = row[j]
            row[j] = tmp
        j = j + 1
    tmp = row[high]
    row[high] = row[i + 1]
    row[i + 1] = tmp
    return i + 1 

# Функция быстрой сортировки
def quicksort(row, low, high):
    if low < high:
        p = partition(row, low, high)
        quicksort(row, low, p - 1)
        quicksort(row, p + 1, high)

In [13]:
# Функция, формирующая отсортированную матрицу
def using_sort(matrix, sort_type = 'none'):
    sort_matrix = np.zeros(matrix.shape)
    atime = 0;
    
    # Если выбрана сортировка обменом
    if sort_type == 'bubble':
        sort_matrix = matrix.copy()
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            bubblesort(sort_matrix[i,:])
        t2 = time.process_time()
        atime = t2 - t1
    
    # Если выбрана быстрая сортировка
    elif sort_type == 'quick':
        sort_matrix = matrix.copy()
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            quicksort(sort_matrix[i,:], 0, sort_matrix.shape[1] - 1)
        t2 = time.process_time()
        atime = t2 - t1
    
    # В противном случае выбирается стандартная функция сортировки NumPy
    else:
        t1 = time.process_time()
        for i in range (0, len(matrix)):
            sort_matrix[i] = np.sort(matrix[i,:])
        t2 = time.process_time()
        atime = t2 - t1

    # Вывод результатов на экран и их возвращение функцией
    print('Время выполнения сортировки (в секундах): ', atime)
    print('Результат:\n', sort_matrix, "\n")
    return sort_matrix

In [14]:
# Вызов каждого метода сортировки с выводом времени выполнения и отсортированной матрицы

# Сортировка обменом
print('Сортировка обменом')
a = using_sort(matrix, 'bubble')

# Быстрая сортировка
print('Быстрая сортировка')
a = using_sort(matrix, 'quick')

# Стандартная функция сортировки
print('Стандартная функция сортировки NumPy')
a = using_sort(matrix)

Сортировка обменом
Время выполнения сортировки (в секундах):  122.53125
Результат:
 [[-994. -994. -987. ...  990.  995.  999.]
 [-999. -995. -991. ...  972.  987.  988.]
 [-996. -993. -987. ...  984.  987.  990.]
 ...
 [-991. -988. -983. ...  993.  994.  996.]
 [-997. -991. -982. ...  991.  993.  999.]
 [-996. -993. -982. ...  985.  992.  994.]] 

Быстрая сортировка
Время выполнения сортировки (в секундах):  3.625
Результат:
 [[-994. -994. -987. ...  990.  995.  999.]
 [-999. -995. -991. ...  972.  987.  988.]
 [-996. -993. -987. ...  984.  987.  990.]
 ...
 [-991. -988. -983. ...  993.  994.  996.]
 [-997. -991. -982. ...  991.  993.  999.]
 [-996. -993. -982. ...  985.  992.  994.]] 

Стандартная функция сортировки NumPy
Время выполнения сортировки (в секундах):  0.03125
Результат:
 [[-994. -994. -987. ...  990.  995.  999.]
 [-999. -995. -991. ...  972.  987.  988.]
 [-996. -993. -987. ...  984.  987.  990.]
 ...
 [-991. -988. -983. ...  993.  994.  996.]
 [-997. -991. -982. ...  99

### Вывод:
В ходе данной лабораторной работы я научилась реализовывать разные виды сортировок и сравнила время их работы для выбора наиболее эффективной.